name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      # Gerar Snake Animation
      - name: Gerar Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: LemesdeMorais
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Fazer deploy da animação no GitHub Pages
      - name: Publicar no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
